# Generated by Django 3.1 on 2021-08-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.SmallIntegerField(verbose_name='Значение'),
        ),
    ]
